name: Dispatch Blog Deploy Workflow

on:
  push:
    branches:
      - dev

jobs:
  trigger-blog-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch remote blog autodeploy.yml
        env:
          REPO: ${{ secrets.BLOG_REPO }}
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            https://api.github.com/repos/$REPO/actions/workflows/autodeploy.yml/dispatches \
            -d '{"ref":"master"}'